In [1]:
import numpy as np

## NumPy: criação de matrizes

In [2]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
np.eye(5, 5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [6]:
lista_python = [1, 2, 3, 4, 5, 6, 7, 8 ]
np.array(lista_python)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.array(lista_python).reshape(2, -1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.array(np.arange(0, 70, 7)).reshape(5, -1)

array([[ 0,  7],
       [14, 21],
       [28, 35],
       [42, 49],
       [56, 63]])

In [9]:
a = np.array(np.arange(0, 16)).reshape(4, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.linspace(1, 15, 16).reshape(4, -1)

array([[ 1.        ,  1.93333333,  2.86666667,  3.8       ],
       [ 4.73333333,  5.66666667,  6.6       ,  7.53333333],
       [ 8.46666667,  9.4       , 10.33333333, 11.26666667],
       [12.2       , 13.13333333, 14.06666667, 15.        ]])

In [11]:
np.logspace(1, 15, 16).reshape(4, -1)

array([[1.00000000e+01, 8.57695899e+01, 7.35642254e+02, 6.30957344e+03],
       [5.41169527e+04, 4.64158883e+05, 3.98107171e+06, 3.41454887e+07],
       [2.92864456e+08, 2.51188643e+09, 2.15443469e+10, 1.84784980e+11],
       [1.58489319e+12, 1.35935639e+13, 1.16591440e+14, 1.00000000e+15]])

In [12]:
np.random.normal(loc=0.0, scale=1.0, size=(4, 4))

array([[-1.10284277,  1.22922119, -1.52283191,  0.83165561],
       [ 0.91339414,  0.81621042, -1.80267792,  0.3625168 ],
       [-0.93606761,  0.24358855,  0.64042409, -0.76276265],
       [-0.28609315, -0.07913815,  1.03141317,  0.35793688]])

In [56]:
tridim = np.array(np.arange(0, 27)).reshape(3, 3, -1)
tridim

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [57]:
bloco = 2
linha = 1
coluna = 0
tridim[bloco, linha, coluna]

21

In [60]:
qd = np.array(np.arange(0, 81)).reshape(3, 3, 3, -1)
qd

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

## NumPy - funções

In [66]:
teste = np.arange(-10, 10, 2).reshape(5, -1)
teste

array([[-10,  -8],
       [ -6,  -4],
       [ -2,   0],
       [  2,   4],
       [  6,   8]])

In [67]:
np.sum(teste)

-10

In [68]:
teste * 5

array([[-50, -40],
       [-30, -20],
       [-10,   0],
       [ 10,  20],
       [ 30,  40]])

In [69]:
teste / 3

array([[-3.33333333, -2.66666667],
       [-2.        , -1.33333333],
       [-0.66666667,  0.        ],
       [ 0.66666667,  1.33333333],
       [ 2.        ,  2.66666667]])

In [71]:
np.sqrt(np.array([ 1, 2, 3, 4, 9, 16 ]).reshape(3, -1))

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [3.        , 4.        ]])

In [72]:
np.sqrt(np.array([ 1, 2, 3, 4, 9, -2 ]).reshape(3, -1))

/home/jtoledo/projects/github/numpy_pandas/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [3.        ,        nan]])

In [15]:
np.sqrt(np.array([ 2, 3, 4, 9, 16, -2+0J ]).reshape(3, -1))

array([[1.41421356+0.j        , 1.73205081+0.j        ],
       [2.        +0.j        , 3.        +0.j        ],
       [4.        +0.j        , 0.        +1.41421356j]])

In [ ]:
a = np.arange(1, 26).reshape(5, -1)

In [93]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [94]:
a * 5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125]])

In [95]:
a + 5

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [96]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [87]:
b = np.arange(10, 260, 10).reshape(5, -1)

In [89]:
b

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [91]:
a * b

array([[  10,   40,   90,  160,  250],
       [ 360,  490,  640,  810, 1000],
       [1210, 1440, 1690, 1960, 2250],
       [2560, 2890, 3240, 3610, 4000],
       [4410, 4840, 5290, 5760, 6250]])

In [90]:
np.matmul(a, b)

array([[ 2150,  2300,  2450,  2600,  2750],
       [ 4900,  5300,  5700,  6100,  6500],
       [ 7650,  8300,  8950,  9600, 10250],
       [10400, 11300, 12200, 13100, 14000],
       [13150, 14300, 15450, 16600, 17750]])

## NumPy - álgebra linear

In [16]:
b = np.random.random(16).reshape(4, 4)
b

array([[0.18141406, 0.35429984, 0.89687568, 0.83520374],
       [0.45610414, 0.57056919, 0.10473303, 0.65799221],
       [0.24159104, 0.55064035, 0.01675039, 0.42076861],
       [0.67525249, 0.07412004, 0.02111621, 0.79964152]])

In [17]:
import numpy.linalg as la
la.inv(b)

array([[ -1.64260396,  17.51839709, -16.55894211,  -3.98625709],
       [ -0.36815152,   3.79150535,  -1.62250419,  -1.88159389],
       [  0.27597232,   9.29051916,  -9.40246457,  -2.98548822],
       [  1.41392399, -15.39008175,  14.38178373,   4.86997729]])

In [18]:
(eigenvalues, eigenvector) = la.eig(b)

In [19]:
eigenvalues

array([ 1.73655879+0.j        ,  0.22304299+0.j        ,
       -0.19561331+0.11957977j, -0.19561331-0.11957977j])

In [20]:
eigenvector

array([[-0.59161074+0.j        , -0.47537364+0.j        ,
        -0.80329566+0.j        , -0.80329566-0.j        ],
       [-0.53389142+0.j        , -0.43494278+0.j        ,
         0.0466474 -0.031134j  ,  0.0466474 +0.031134j  ],
       [-0.37074286+0.j        , -0.43559469+0.j        ,
        -0.18075419-0.16020501j, -0.18075419+0.16020501j],
       [-0.47697634+0.j        ,  0.62857135+0.j        ,
         0.53693643+0.07023057j,  0.53693643-0.07023057j]])

## Pandas

In [21]:
import pandas as pd

In [100]:
dic = { "Coluna 1": ["v1", "v2", "v3", "v4"],
        "Coluna 2": ["v1c2", "v2c2", "v3c2", "v4c2"] }
df_dic = pd.DataFrame(dic, index=["primeira", "segunda", "terceira", "quarta"])

In [101]:
df_dic

Coluna 1 Coluna 2
primeira       v1     v1c2
segunda        v2     v2c2
terceira       v3     v3c2
quarta         v4     v4c2

In [105]:
lista = [["v1", "v1c2"],
         ["v2", "v2c2"],
         ["v3", "v3c2"],
         ["v4", "v4c2"]]

In [106]:
df_lista = pd.DataFrame(lista,
                        index=["primeira", "segunda", "terceira", "quarta"])
df_lista

0     1
primeira  v1  v1c2
segunda   v2  v2c2
terceira  v3  v3c2
quarta    v4  v4c2

In [107]:
df_lista.columns = ["Coluna 1", "Coluna 2"]

In [108]:
df_lista

Coluna 1 Coluna 2
primeira       v1     v1c2
segunda        v2     v2c2
terceira       v3     v3c2
quarta         v4     v4c2

In [119]:
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [120]:
df_array = pd.DataFrame(a,
                        index=range(1, 6),
                        columns=list("ABCDE"))

In [121]:
df_array

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [122]:
df = pd.DataFrame(np.arange(1, 26).reshape(5, -1),
                  index=["L1", "L2", "L3", "L4", "L5"],
                  columns=["C1", "C2", "C3", "C4", "C5"])
df

C1  C2  C3  C4  C5
L1   1   2   3   4   5
L2   6   7   8   9  10
L3  11  12  13  14  15
L4  16  17  18  19  20
L5  21  22  23  24  25

In [123]:
df["C3"]

L1     3
L2     8
L3    13
L4    18
L5    23
Name: C3, dtype: int64

In [135]:
df[2:4]

C1  C2  C3  C4  C5
L3  11  12  13  14  15
L4  16  17  18  19  20

In [ ]:
df.iloc[]

In [22]:
cervejas = pd.DataFrame([["Vedett", "IPA", "Bélgica", 0.33, 5.5],
                         ["Eisenbahn", "Strong Golden Ale", "Brasil", 0.355, 8.0],
                         ["Belhaven", "Rich Scottish Ale", "Escócia", 0.33, 7.4],
                         ["Robinsons", "Premium Britisch Beer", "Inglaterra", 0.5, 4.7],
                         ["Brewdog", "IPA", "Escócia", 0.33, 5.6],
                         ["Fuller's", "Superior Strong Ale", "Inglaterra", 0.5, 8.5],
                         ["Goose", "Session IPA", "Brasil", 0.355, 4.1]],
                        index=["Vedett IPA", "Eisenbahn", "90 Wee Heavy", "Trooper", "Punk IPA", "Golden Pride", "Midway"],
                        columns=["Fabricante", "Tipo", "País", "Volume", "Graduação Alcoólica"])

In [23]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   
Midway            Goose            Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6  
Golden Pride                  8.5  
Midway                        4.1

In [24]:
cervejas['Volume'].rank()

Vedett IPA      2.0
Eisenbahn       4.5
90 Wee Heavy    2.0
Trooper         6.5
Punk IPA        2.0
Golden Pride    6.5
Midway          4.5
Name: Volume, dtype: float64

In [25]:
cervejas.sort_values(['Volume'])

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
Midway            Goose            Session IPA      Brasil   0.355   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   

              Graduação Alcoólica  
Vedett IPA                    5.5  
90 Wee Heavy                  7.4  
Punk IPA                      5.6  
Eisenbahn                     8.0  
Midway                        4.1  
Trooper                       4.7  
Golden Pride                  8.5

In [26]:
cervejas['Graduação Alcoólica'].max()

8.5

In [27]:
cervejas['Graduação Alcoólica'].idxmax()

'Golden Pride'

In [28]:
cervejas['Graduação Alcoólica'].idxmin()

'Midway'

In [29]:
cervejas.take([2, 4, -2])

Fabricante                 Tipo        País  Volume  \
90 Wee Heavy   Belhaven    Rich Scottish Ale     Escócia    0.33   
Punk IPA        Brewdog                  IPA     Escócia    0.33   
Golden Pride   Fuller's  Superior Strong Ale  Inglaterra    0.50   

              Graduação Alcoólica  
90 Wee Heavy                  7.4  
Punk IPA                      5.6  
Golden Pride                  8.5

In [30]:
cervejas.iloc[[2, 4, -2]]

Fabricante                 Tipo        País  Volume  \
90 Wee Heavy   Belhaven    Rich Scottish Ale     Escócia    0.33   
Punk IPA        Brewdog                  IPA     Escócia    0.33   
Golden Pride   Fuller's  Superior Strong Ale  Inglaterra    0.50   

              Graduação Alcoólica  
90 Wee Heavy                  7.4  
Punk IPA                      5.6  
Golden Pride                  8.5

In [31]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   
Midway            Goose            Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6  
Golden Pride                  8.5  
Midway                        4.1

In [32]:
cervejas.iat[1, 2]

'Brasil'

In [33]:
cervejas.iat[5, 4]

8.5

In [34]:
cervejas.iat[0, 0]

'Vedett'

In [35]:
cervejas.at['Trooper', 'Volume']

0.5