In [1]:
import numpy as np

## NumPy: criação de matrizes

In [2]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
np.eye(5, 5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [6]:
lista_python = [1, 2, 3, 4, 5, 6, 7, 8 ]
np.array(lista_python)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.array(lista_python).reshape(2, -1) 8

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.arange(0, 70, 7).reshape(5, -1)

array([[ 0,  7],
       [14, 21],
       [28, 35],
       [42, 49],
       [56, 63]])

In [9]:
a = np.arange(0, 16).reshape(4, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.linspace(1, 15, 16).reshape(4, -1)

array([[ 1.        ,  1.93333333,  2.86666667,  3.8       ],
       [ 4.73333333,  5.66666667,  6.6       ,  7.53333333],
       [ 8.46666667,  9.4       , 10.33333333, 11.26666667],
       [12.2       , 13.13333333, 14.06666667, 15.        ]])

In [11]:
np.logspace(1, 15, 16).reshape(4, -1)

array([[1.00000000e+01, 8.57695899e+01, 7.35642254e+02, 6.30957344e+03],
       [5.41169527e+04, 4.64158883e+05, 3.98107171e+06, 3.41454887e+07],
       [2.92864456e+08, 2.51188643e+09, 2.15443469e+10, 1.84784980e+11],
       [1.58489319e+12, 1.35935639e+13, 1.16591440e+14, 1.00000000e+15]])

In [12]:
np.random.normal(loc=0.0, scale=1.0, size=(4, 4))

array([[-0.70488753, -1.62251741,  0.27032163,  0.11240774],
       [-0.83352446,  1.00506809,  0.4327122 ,  0.56848337],
       [ 0.31280077,  0.21126553, -0.31739769, -0.53282451],
       [-0.26413117,  2.28088858,  1.02745266, -1.24045474]])

In [13]:
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    ==================== =========================================================
    Utility functions
    random_sample        Uniformly distributed floats over ``[0, 1)``.
    random               Alias for `random_sample`.
    bytes                Uniformly distributed random bytes.
    random_integers      Uniformly distributed integers in a given range.
    permutation          Randomly permute a sequence / generate a random sequence.
    shuffle              Randomly permute a sequence in place.
    seed                 Seed the random number generator.
    choice               Random sample from 1-D array.
    
    ==================== =========================================================
    
    ==================== =========================================================
    Compatibility functions
    rand                 Uniformly distributed values.
    randn

#### Indexação

In [14]:
a = np.arange(1, 26).reshape(5, 5)

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
a[0, 3]

4

In [17]:
a[1]

array([ 6,  7,  8,  9, 10])

In [18]:
a[:, 3]

array([ 4,  9, 14, 19, 24])

In [19]:
a[2:4, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20]])

### Arrays com mais dimensões

In [20]:
tridim = np.array(np.arange(0, 27)).reshape(3, 3, -1)
tridim

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [21]:
camada = 2
linha = 1
coluna = 0
tridim[camada, linha, coluna]

21

In [22]:
qd = np.array(np.arange(0, 81)).reshape(3, 3, 3, -1)
qd

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

## NumPy - operações

In [23]:
teste = np.array([ 1, 2, 3, 4, 9, 16 ]).reshape(3, -1)
teste

array([[ 1,  2],
       [ 3,  4],
       [ 9, 16]])

In [24]:
np.sum(teste)

35

In [25]:
teste * 5

array([[ 5, 10],
       [15, 20],
       [45, 80]])

In [26]:
teste / 3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333],
       [3.        , 5.33333333]])

In [27]:
np.sqrt(teste)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [3.        , 4.        ]])

In [28]:
teste[2, 1] = -2

In [29]:
np.sqrt(np.array([ 1, 2, 3, 4, 9, -2 ]).reshape(3, -1))

/home/jtoledo/projects/github/numpy_pandas/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [3.        ,        nan]])

In [30]:
# ERRO: can't convert complex to int
# teste[2, 1] = 2 + 0j

In [31]:
teste.dtype

dtype('int64')

In [32]:
teste_complexos = np.array([ 2, 3, 4, 9, 16, -2+0J ]).reshape(3, -1)

In [33]:
teste_complexos.dtype

dtype('complex128')

In [34]:
np.sqrt(teste_complexos)

array([[1.41421356+0.j        , 1.73205081+0.j        ],
       [2.        +0.j        , 3.        +0.j        ],
       [4.        +0.j        , 0.        +1.41421356j]])

In [35]:
a = np.arange(1, 26).reshape(5, -1)

In [36]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
a * 5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125]])

In [38]:
a + 5

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
b = np.arange(10, 260, 10).reshape(5, -1)

In [41]:
b

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [42]:
a * b

array([[  10,   40,   90,  160,  250],
       [ 360,  490,  640,  810, 1000],
       [1210, 1440, 1690, 1960, 2250],
       [2560, 2890, 3240, 3610, 4000],
       [4410, 4840, 5290, 5760, 6250]])

In [43]:
np.matmul(a, b)

array([[ 2150,  2300,  2450,  2600,  2750],
       [ 4900,  5300,  5700,  6100,  6500],
       [ 7650,  8300,  8950,  9600, 10250],
       [10400, 11300, 12200, 13100, 14000],
       [13150, 14300, 15450, 16600, 17750]])

## NumPy - álgebra linear

In [44]:
b = np.random.random(16).reshape(4, 4)
b

array([[0.27612085, 0.87671691, 0.35595651, 0.65504721],
       [0.19052851, 0.8988717 , 0.75522404, 0.21794157],
       [0.2699163 , 0.64537542, 0.75010158, 0.14046711],
       [0.31558746, 0.96639022, 0.25296085, 0.60475773]])

In [45]:
import numpy.linalg as la
la.inv(b)

array([[-3.8839332 , -5.83856986,  6.06859855,  4.90144738],
       [-2.97477865,  2.36316605, -1.91723862,  2.81583389],
       [ 2.91569986,  0.22168975,  0.88785077, -3.44427231],
       [ 5.5608379 , -0.82221353, -0.47451134, -3.9631798 ]])

In [46]:
(eigenvalues, eigenvector) = la.eig(b)

In [47]:
eigenvalues

array([ 2.00630831, -0.08535722,  0.27753914,  0.33136163])

In [48]:
eigenvector

array([[-0.53892005, -0.74941535, -0.70721721,  0.69657575],
       [-0.48957796, -0.22112356,  0.42437714, -0.38186535],
       [-0.42725451,  0.3231666 , -0.00755739, -0.06312142],
       [-0.53603375,  0.53389546, -0.56541201,  0.60413307]])

### NumPy: outras funções - VEJA A DOCUMENTAÇÃO!

## Pandas

In [49]:
import pandas as pd

In [51]:
df_dic

Coluna 1 Coluna 2 Coluna 3  Coluna 4  Coluna 5
primeira       v1     v1c2        A      1.00  (1.1+0j)
segunda        v2     v2c2        B      2.50    (2+0j)
terceira       v3     v3c2        C      3.75    (3+0j)
quarta         v4     v4c2        D      5.00    (4+0j)

In [52]:
lista = [["v1", "v1c2", "A"],
         ["v2", "v2c2", "B"],
         ["v3", "v3c2", "C"],
         ["v4", "v4c2", "D"]]

In [53]:
df_lista = pd.DataFrame(lista,
                        index=["primeira", "segunda", "terceira", "quarta"])
df_lista

0     1  2
primeira  v1  v1c2  A
segunda   v2  v2c2  B
terceira  v3  v3c2  C
quarta    v4  v4c2  D

In [54]:
df_lista.columns = ["Coluna 1", "Coluna 2", "Coluna 3"]

In [55]:
df_lista

Coluna 1 Coluna 2 Coluna 3
primeira       v1     v1c2        A
segunda        v2     v2c2        B
terceira       v3     v3c2        C
quarta         v4     v4c2        D

In [56]:
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
df_array = pd.DataFrame(a,
                        index=range(1, 6),
                        columns=list("ABCDE"))

In [58]:
df_array

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

## Indexing

In [59]:
df = pd.DataFrame(np.arange(1, 26).reshape(5, -1),
                  index=["L0", "L1", "L2", "L3", "L4"],
                  columns=["C0", "C1", "C2", "C3", "C4"])
df

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L1   6   7   8   9  10
L2  11  12  13  14  15
L3  16  17  18  19  20
L4  21  22  23  24  25

#### Usando colchetes

In [60]:
df["C3"]

L0     4
L1     9
L2    14
L3    19
L4    24
Name: C3, dtype: int64

___Pegadinha___: e se eu quiser a segunda e a terceira colunas?

In [61]:
df[2:4]

C0  C1  C2  C3  C4
L2  11  12  13  14  15
L3  16  17  18  19  20

Pois é... Não é bem o que esperávamos...

##### Sem ambiguidade: `loc` e `iloc`

In [62]:
df

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L1   6   7   8   9  10
L2  11  12  13  14  15
L3  16  17  18  19  20
L4  21  22  23  24  25

In [63]:
# df.iloc[ linhas,  colunas ]
df.iloc[3, 0]

16

In [64]:
df.iloc[-2:, :2]

C0  C1
L3  16  17
L4  21  22

In [65]:
df.iloc[-2:, -2:]

C3  C4
L3  19  20
L4  24  25

In [66]:
df.iloc[[0, 2, 4], [1, 3]]

C1  C3
L0   2   4
L2  12  14
L4  22  24

In [67]:
df.iloc[:, 3:4]

C3
L0   4
L1   9
L2  14
L3  19
L4  24

In [68]:
df

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L1   6   7   8   9  10
L2  11  12  13  14  15
L3  16  17  18  19  20
L4  21  22  23  24  25

In [69]:
df.loc[:, "C1"]

L0     2
L1     7
L2    12
L3    17
L4    22
Name: C1, dtype: int64

#### `loc` com índices numéricos

In [70]:
df_array

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [71]:
df_array.loc[5, "A"]

21

##### `at` e `iat`

In [72]:
df.at["L2", "C3"]

14

In [73]:
df.iat[3, 4]

20

### Filters

In [74]:
df

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L1   6   7   8   9  10
L2  11  12  13  14  15
L3  16  17  18  19  20
L4  21  22  23  24  25

In [75]:
df['C2'] % 2 == 0

L0    False
L1     True
L2    False
L3     True
L4    False
Name: C2, dtype: bool

In [76]:
filtro = df['C2'] % 2 == 0
filtro

L0    False
L1     True
L2    False
L3     True
L4    False
Name: C2, dtype: bool

In [77]:
df[filtro]

C0  C1  C2  C3  C4
L1   6   7   8   9  10
L3  16  17  18  19  20

In [78]:
df[~filtro]

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L2  11  12  13  14  15
L4  21  22  23  24  25

##### _deprecated_: `ix`

In [79]:
df.ix[3, 2]

/home/jtoledo/projects/github/numpy_pandas/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


18

(uma hora até aqui está muito bom...)

### Operações Básicas

(copiar DataFrame da parte_1, do meio para o final)

In [80]:
cervejas = pd.DataFrame([["Vedett", "IPA", "Bélgica", 0.33, 5.5],
                         ["Eisenbahn", "Strong Golden Ale", "Brasil", 0.355, 8.0],
                         ["Belhaven", "Rich Scottish Ale", "Escócia", 0.33, 7.4],
                         ["Robinsons", "Premium Britisch Beer", "Inglaterra", 0.5, 4.7],
                         ["Brewdog", "IPA", "Escócia", 0.33, 5.6],
                         ["Fuller's", "Superior Strong Ale", "Inglaterra", 0.5, 8.5],
                         ["Goose", "Session IPA", "Brasil", 0.355, 4.1]],
                        index=["Vedett IPA", "Eisenbahn", "90 Wee Heavy", "Trooper", "Punk IPA", "Golden Pride", "Midway"],
                        columns=["Fabricante", "Tipo", "País", "Volume", "Graduação Alcoólica"])

In [81]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   
Midway            Goose            Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6  
Golden Pride                  8.5  
Midway                        4.1

In [82]:
cervejas.head()

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6

In [83]:
cervejas.head(3)

Fabricante               Tipo     País  Volume  \
Vedett IPA       Vedett                IPA  Bélgica   0.330   
Eisenbahn     Eisenbahn  Strong Golden Ale   Brasil   0.355   
90 Wee Heavy   Belhaven  Rich Scottish Ale  Escócia   0.330   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4

In [84]:
cervejas.tail(2)

Fabricante                 Tipo        País  Volume  \
Golden Pride   Fuller's  Superior Strong Ale  Inglaterra   0.500   
Midway            Goose          Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Golden Pride                  8.5  
Midway                        4.1

In [85]:
cervejas.describe()

Volume  Graduação Alcoólica
count  7.000000             7.000000
mean   0.385714             6.257143
std    0.078868             1.705733
min    0.330000             4.100000
25%    0.330000             5.100000
50%    0.355000             5.600000
75%    0.427500             7.700000
max    0.500000             8.500000

In [86]:
# cervejas.transpose() é a mesma coisa
cervejas.T

Vedett IPA          Eisenbahn       90 Wee Heavy  \
Fabricante              Vedett          Eisenbahn           Belhaven   
Tipo                       IPA  Strong Golden Ale  Rich Scottish Ale   
País                   Bélgica             Brasil            Escócia   
Volume                    0.33              0.355               0.33   
Graduação Alcoólica        5.5                  8                7.4   

                                   Trooper Punk IPA         Golden Pride  \
Fabricante                       Robinsons  Brewdog             Fuller's   
Tipo                 Premium Britisch Beer      IPA  Superior Strong Ale   
País                            Inglaterra  Escócia           Inglaterra   
Volume                                 0.5     0.33                  0.5   
Graduação Alcoólica                    4.7      5.6                  8.5   

                          Midway  
Fabricante                 Goose  
Tipo                 Session IPA  
País                      Brasil  
Volume                     0.355  
Graduação Alcoólica          4.1

In [87]:
cervejas.sort_values(['Volume', 'Graduação Alcoólica'])

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Midway            Goose            Session IPA      Brasil   0.355   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Punk IPA                      5.6  
90 Wee Heavy                  7.4  
Midway                        4.1  
Eisenbahn                     8.0  
Trooper                       4.7  
Golden Pride                  8.5

In [88]:
cervejas.sort_values(['Graduação Alcoólica'], ascending=False).sort_values('Volume')

Fabricante                   Tipo        País  Volume  \
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
Midway            Goose            Session IPA      Brasil   0.355   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   

              Graduação Alcoólica  
90 Wee Heavy                  7.4  
Punk IPA                      5.6  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
Midway                        4.1  
Golden Pride                  8.5  
Trooper                       4.7

In [89]:
cervejas['Graduação Alcoólica'].max()

8.5

In [90]:
cervejas['Graduação Alcoólica'].idxmax()

'Golden Pride'

In [91]:
cervejas['Graduação Alcoólica'].idxmin()

'Midway'

In [92]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   
Midway            Goose            Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6  
Golden Pride                  8.5  
Midway                        4.1

Volume em MLs

In [93]:
cervejas['Volume'] * 1000

Vedett IPA      330.0
Eisenbahn       355.0
90 Wee Heavy    330.0
Trooper         500.0
Punk IPA        330.0
Golden Pride    500.0
Midway          355.0
Name: Volume, dtype: float64

In [94]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   
Midway            Goose            Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6  
Golden Pride                  8.5  
Midway                        4.1

In [95]:
cervejas['Volume'] *= 1000

In [96]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   355.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   
Midway            Goose            Session IPA      Brasil   355.0   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6  
Golden Pride                  8.5  
Midway                        4.1

In [97]:
cervejas['Local de Produção'] = None

In [98]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   355.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   
Midway            Goose            Session IPA      Brasil   355.0   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5              None  
Eisenbahn                     8.0              None  
90 Wee Heavy                  7.4              None  
Trooper                       4.7              None  
Punk IPA                      5.6              None  
Golden Pride                  8.5              None  
Midway                        4.1              None

In [99]:
cervejas[cervejas['País'] != 'Brasil']

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5              None  
90 Wee Heavy                  7.4              None  
Trooper                       4.7              None  
Punk IPA                      5.6              None  
Golden Pride                  8.5              None

In [100]:
cervejas.loc[cervejas['País'] != 'Brasil', 'Local de Produção'] = 'Exterior'

In [101]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   355.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   
Midway            Goose            Session IPA      Brasil   355.0   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5          Exterior  
Eisenbahn                     8.0              None  
90 Wee Heavy                  7.4          Exterior  
Trooper                       4.7          Exterior  
Punk IPA                      5.6          Exterior  
Golden Pride                  8.5          Exterior  
Midway                        4.1              None

In [102]:
cervejas.loc['Eisenbahn', 'Local de Produção'] = 'Blumenau'
cervejas.loc['Midway', 'Local de Produção'] = 'São Paulo'

In [103]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   355.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   
Midway            Goose            Session IPA      Brasil   355.0   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5          Exterior  
Eisenbahn                     8.0          Blumenau  
90 Wee Heavy                  7.4          Exterior  
Trooper                       4.7          Exterior  
Punk IPA                      5.6          Exterior  
Golden Pride                  8.5          Exterior  
Midway                        4.1         São Paulo

In [104]:
# a ordem e tipos dos dados deve ser igual à das colunas existentes!
cervejas.loc['Skol'] = ['AMBEV', 'Pilsen', 'Brasil', 0.35, 4.5, '***']

In [105]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica  330.00   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil  355.00   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia  330.00   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra  500.00   
Punk IPA        Brewdog                    IPA     Escócia  330.00   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra  500.00   
Midway            Goose            Session IPA      Brasil  355.00   
Skol              AMBEV                 Pilsen      Brasil    0.35   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5          Exterior  
Eisenbahn                     8.0          Blumenau  
90 Wee Heavy                  7.4          Exterior  
Trooper                       4.7          Exterior  
Punk IPA                      5.6          Exterior  
Golden Pride                  8.5          Exterior  
Midway                        4.1         São Paulo  
Skol                          4.5               ***

## E se eu quisesse tomar uma garrafa de cada uma, quanto líquido eu consumiria?

In [106]:
cervejas.sum()

Fabricante             VedettEisenbahnBelhavenRobinsonsBrewdogFuller'...
Tipo                   IPAStrong Golden AleRich Scottish AlePremium B...
País                   BélgicaBrasilEscóciaInglaterraEscóciaInglaterr...
Volume                                                           2700.35
Graduação Alcoólica                                                 48.3
Local de Produção      ExteriorBlumenauExteriorExteriorExteriorExteri...
dtype: object

In [107]:
cervejas.sum(numeric_only=True)

Volume                 2700.35
Graduação Alcoólica      48.30
dtype: float64

In [108]:
cervejas['Volume'].sum()

2700.35

## É muita cerveja!

In [109]:
cervejas.drop('Skol')

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   355.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   
Midway            Goose            Session IPA      Brasil   355.0   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5          Exterior  
Eisenbahn                     8.0          Blumenau  
90 Wee Heavy                  7.4          Exterior  
Trooper                       4.7          Exterior  
Punk IPA                      5.6          Exterior  
Golden Pride                  8.5          Exterior  
Midway                        4.1         São Paulo

In [110]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica  330.00   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil  355.00   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia  330.00   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra  500.00   
Punk IPA        Brewdog                    IPA     Escócia  330.00   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra  500.00   
Midway            Goose            Session IPA      Brasil  355.00   
Skol              AMBEV                 Pilsen      Brasil    0.35   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5          Exterior  
Eisenbahn                     8.0          Blumenau  
90 Wee Heavy                  7.4          Exterior  
Trooper                       4.7          Exterior  
Punk IPA                      5.6          Exterior  
Golden Pride                  8.5          Exterior  
Midway                        4.1         São Paulo  
Skol                          4.5               ***

In [111]:
cervejas.drop('Skol', inplace=True)

In [112]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   355.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   
Midway            Goose            Session IPA      Brasil   355.0   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5          Exterior  
Eisenbahn                     8.0          Blumenau  
90 Wee Heavy                  7.4          Exterior  
Trooper                       4.7          Exterior  
Punk IPA                      5.6          Exterior  
Golden Pride                  8.5          Exterior  
Midway                        4.1         São Paulo

### Apply

In [113]:
def get_classificacao(linha):
    ga = linha['Graduação Alcoólica']
    if (ga < 5):
        return 'light'
    elif (ga < 8):
        return 'ok'
    else:
        return 'strong'

In [114]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   355.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   
Midway            Goose            Session IPA      Brasil   355.0   

              Graduação Alcoólica Local de Produção  
Vedett IPA                    5.5          Exterior  
Eisenbahn                     8.0          Blumenau  
90 Wee Heavy                  7.4          Exterior  
Trooper                       4.7          Exterior  
Punk IPA                      5.6          Exterior  
Golden Pride                  8.5          Exterior  
Midway                        4.1         São Paulo

In [115]:
cervejas['Classificação'] = cervejas.apply(get_classificacao, axis='columns')

In [116]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   330.0   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   355.0   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   330.0   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   500.0   
Punk IPA        Brewdog                    IPA     Escócia   330.0   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   500.0   
Midway            Goose            Session IPA      Brasil   355.0   

              Graduação Alcoólica Local de Produção Classificação  
Vedett IPA                    5.5          Exterior            ok  
Eisenbahn                     8.0          Blumenau        strong  
90 Wee Heavy                  7.4          Exterior            ok  
Trooper                       4.7          Exterior         light  
Punk IPA                      5.6          Exterior            ok  
Golden Pride                  8.5          Exterior        strong  
Midway                        4.1         São Paulo         light

## Funções são ___First Class Citizens___ em Python!

### Loading & Saving

In [117]:
goog = pd.read_csv('GOOG.csv')
goog.head()

Date;Open;High;Low;Close;Adj Close;Volume
19/08/2004;49 676899;51 693783;47 669952;49 845802;49                           845802;44994500
20/08/2004;50 178635;54 187561;49 925285;53 805050;53                           805050;23005800
23/08/2004;55 017166;56 373344;54 172661;54 346527;54                           346527;18393200
24/08/2004;55 260582;55 439419;51 450363;52 096165;52                           096165;15361800
25/08/2004;52 140873;53 651051;51 604362;52 657513;52                            657513;9257400

In [118]:
goog = pd.read_csv('GOOG.csv',
                   sep=';')
goog.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  19/08/2004  49,676899  51,693783  47,669952  49,845802  49,845802  44994500
1  20/08/2004  50,178635  54,187561  49,925285  53,805050  53,805050  23005800
2  23/08/2004  55,017166  56,373344  54,172661  54,346527  54,346527  18393200
3  24/08/2004  55,260582  55,439419  51,450363  52,096165  52,096165  15361800
4  25/08/2004  52,140873  53,651051  51,604362  52,657513  52,657513   9257400

In [119]:
goog.dtypes

Date         object
Open         object
High         object
Low          object
Close        object
Adj Close    object
Volume        int64
dtype: object

In [120]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',')
goog.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  19/08/2004  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1  20/08/2004  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2  23/08/2004  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3  24/08/2004  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4  25/08/2004  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [121]:
goog.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [122]:
goog.sort_values('Date').head()

Date        Open        High         Low       Close   Adj Close  \
114   01/02/2005   96.561958   97.694588   94.699074   95.329971   95.329971   
366   01/02/2006  193.258041  199.701141  192.507919  199.591843  199.591843   
617   01/02/2007  251.365112  251.370087  239.209167  239.318466  239.318466   
869   01/02/2008  262.626862  266.601013  253.352188  256.283112  256.283112   
1372  01/02/2010  265.572693  266.173798  263.436584  264.787811  264.787811   

        Volume  
114   37922900  
366   54597700  
617   31521000  
869   35429900  
1372   4530800

In [123]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',',
                   parse_dates=[0])
goog.head()

Date       Open       High        Low      Close  Adj Close    Volume
0 2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1 2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2 2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3 2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4 2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [124]:
goog.dtypes

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [125]:
goog.sort_values('Date').head()

Date       Open       High        Low      Close  Adj Close    Volume
9  2004-01-09  51.018177  51.152302  49.512966  49.801090  49.801090   9206800
30 2004-01-10  64.977386  66.686272  64.033524  65.861633  65.861633  15238400
51 2004-01-11  96.149643  98.196327  95.017006  97.381630  97.381630  24608700
72 2004-01-12  90.387115  90.660339  89.194870  89.398552  89.398552  15830400
10 2004-02-09  49.274517  50.854240  49.150326  50.427021  50.427021  15232100

In [126]:
goog.sort_values('Date').tail()

Date         Open         High          Low        Close  \
3663 2019-11-03  1144.449951  1176.189941  1144.449951  1175.760010   
3686 2019-11-04  1203.959961  1207.959961  1200.130005  1204.619995   
3645 2019-12-02  1106.800049  1125.295044  1105.849976  1121.369995   
3664 2019-12-03  1178.260010  1200.000000  1178.260010  1193.199951   
3687 2019-12-04  1210.000000  1218.349976  1208.109985  1217.869995   

        Adj Close   Volume  
3663  1175.760010  1719200  
3686  1204.619995   710200  
3645  1121.369995  1609100  
3664  1193.199951  2013100  
3687  1217.869995   933400

In [127]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',',
                   parse_dates=[0],
                   dayfirst=True)
goog.head()

Date       Open       High        Low      Close  Adj Close    Volume
0 2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1 2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2 2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3 2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4 2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [128]:
goog.sort_values('Date').tail()

Date         Open         High          Low        Close  \
3689 2019-04-16  1225.000000  1230.819946  1220.119995  1227.130005   
3690 2019-04-17  1233.000000  1240.560059  1227.819946  1236.339966   
3691 2019-04-18  1239.180054  1242.000000  1234.609985  1236.369995   
3692 2019-04-22  1235.989990  1249.089966  1228.310059  1248.839966   
3693 2019-04-23  1250.689941  1269.000000  1246.380005  1264.550049   

        Adj Close   Volume  
3689  1227.130005   856300  
3690  1236.339966  1221900  
3691  1236.369995  1331800  
3692  1248.839966   807300  
3693  1264.550049  1319900

In [129]:
goog.sort_values('Date').head()

Date       Open       High        Low      Close  Adj Close    Volume
0 2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1 2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2 2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3 2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4 2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [130]:
goog.dtypes

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [131]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',',
                   parse_dates=[0],
                   dayfirst=True,
                   names=["Data", "Abertura", "Máximo", "Mínimo", "Fechamento", "Fechamento Ajustado", "Volume"])
goog.head()

Data   Abertura     Máximo     Mínimo Fechamento Fechamento Ajustado  \
0        Date       Open       High        Low      Close           Adj Close   
1  19/08/2004  49,676899  51,693783  47,669952  49,845802           49,845802   
2  20/08/2004  50,178635  54,187561  49,925285  53,805050           53,805050   
3  23/08/2004  55,017166  56,373344  54,172661  54,346527           54,346527   
4  24/08/2004  55,260582  55,439419  51,450363  52,096165           52,096165   

     Volume  
0    Volume  
1  44994500  
2  23005800  
3  18393200  
4  15361800

In [132]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',',
                   parse_dates=[0],
                   dayfirst=True,
                   names=["Data", "Abertura", "Máximo", "Mínimo", "Fechamento", "Fechamento Ajustado", "Volume"],
                   skiprows=1)
goog.head()

Data   Abertura     Máximo     Mínimo  Fechamento  \
0 2004-08-19  49.676899  51.693783  47.669952   49.845802   
1 2004-08-20  50.178635  54.187561  49.925285   53.805050   
2 2004-08-23  55.017166  56.373344  54.172661   54.346527   
3 2004-08-24  55.260582  55.439419  51.450363   52.096165   
4 2004-08-25  52.140873  53.651051  51.604362   52.657513   

   Fechamento Ajustado    Volume  
0            49.845802  44994500  
1            53.805050  23005800  
2            54.346527  18393200  
3            52.096165  15361800  
4            52.657513   9257400

In [133]:
xls = pd.read_excel('AAPL_GOOG.xlsx', sheet_name='GOOG')
xls.head()

Date       Open       High        Low      Close  Adj Close    Volume
0 2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1 2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2 2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3 2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4 2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [134]:
xls.dtypes

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [135]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=0, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, doublequote=True, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    Read a comma-separated values (csv) file into DataFrame.
    
    Also supports option

In [136]:
help(pd.read_excel)

Help on function read_excel in module pandas.io.excel:

read_excel(io, sheet_name=0, header=0, names=None, index_col=None, parse_cols=None, usecols=None, squeeze=False, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, keep_default_na=True, verbose=False, parse_dates=False, date_parser=None, thousands=None, comment=None, skip_footer=0, skipfooter=0, convert_float=True, mangle_dupe_cols=True, **kwds)
    Read an Excel file into a pandas DataFrame.
    
    Support both `xls` and `xlsx` file extensions from a local filesystem or URL.
    Support an option to read a single sheet or a list of sheets.
    
    Parameters
    ----------
    io : str, file descriptor, pathlib.Path, ExcelFile or xlrd.Book
        The string could be a URL. Valid URL schemes include http, ftp, s3,
        gcs, and file. For file URLs, a host is expected. For instance, a local
        file could be /path/to/workbook.xlsx.
    sheet_name : st