In [1]:
import numpy as np

## NumPy: criação de matrizes

In [2]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
np.eye(5, 5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [6]:
lista_python = [1, 2, 3, 4, 5, 6, 7, 8 ]
np.array(lista_python)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.array(lista_python).reshape(2, -1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.array(np.arange(0, 70, 7)).reshape(5, -1)

array([[ 0,  7],
       [14, 21],
       [28, 35],
       [42, 49],
       [56, 63]])

In [9]:
a = np.array(np.arange(0, 16)).reshape(4, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.linspace(1, 15, 16).reshape(4, -1)

array([[ 1.        ,  1.93333333,  2.86666667,  3.8       ],
       [ 4.73333333,  5.66666667,  6.6       ,  7.53333333],
       [ 8.46666667,  9.4       , 10.33333333, 11.26666667],
       [12.2       , 13.13333333, 14.06666667, 15.        ]])

In [11]:
np.logspace(1, 15, 16).reshape(4, -1)

array([[1.00000000e+01, 8.57695899e+01, 7.35642254e+02, 6.30957344e+03],
       [5.41169527e+04, 4.64158883e+05, 3.98107171e+06, 3.41454887e+07],
       [2.92864456e+08, 2.51188643e+09, 2.15443469e+10, 1.84784980e+11],
       [1.58489319e+12, 1.35935639e+13, 1.16591440e+14, 1.00000000e+15]])

In [12]:
np.random.normal(loc=0.0, scale=1.0, size=(4, 4))

array([[ 0.47496378, -1.50710769,  0.02920256, -0.14194829],
       [ 0.52997048,  0.67406666,  0.82665144, -1.16259551],
       [ 2.18571879, -0.3924473 ,  1.55579817, -0.20879927],
       [ 0.85025181,  1.12558939, -1.83731828, -0.34542874]])

In [13]:
tridim = np.array(np.arange(0, 27)).reshape(3, 3, -1)
tridim

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
camada = 2
linha = 1
coluna = 0
tridim[camada, linha, coluna]

21

In [15]:
qd = np.array(np.arange(0, 81)).reshape(3, 3, 3, -1)
qd

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]],


       [[[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44]],

        [[45, 46, 47],
         [48, 49, 50],
         [51, 52, 53]]],


       [[[54, 55, 56],
         [57, 58, 59],
         [60, 61, 62]],

        [[63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80]]]])

## NumPy - funções

In [16]:
teste = np.array([ 1, 2, 3, 4, 9, 16 ]).reshape(3, -1)
teste

array([[ 1,  2],
       [ 3,  4],
       [ 9, 16]])

In [17]:
np.sum(teste)

35

In [18]:
teste * 5

array([[ 5, 10],
       [15, 20],
       [45, 80]])

In [19]:
teste / 3

array([[0.33333333, 0.66666667],
       [1.        , 1.33333333],
       [3.        , 5.33333333]])

In [20]:
np.sqrt(teste)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [3.        , 4.        ]])

In [21]:
teste[2, 1] = -2

In [22]:
np.sqrt(np.array([ 1, 2, 3, 4, 9, -2 ]).reshape(3, -1))

/home/jtoledo/projects/github/numpy_pandas/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [3.        ,        nan]])

In [23]:
teste[2, 1] = 2 + 0j

TypeError: can't convert complex to int

In [24]:
teste.dtype

dtype('int64')

In [25]:
teste_complexos = np.array([ 2, 3, 4, 9, 16, -2+0J ]).reshape(3, -1)

In [26]:
teste_complexos.dtype

dtype('complex128')

In [27]:
np.sqrt(teste_complexos)

array([[1.41421356+0.j        , 1.73205081+0.j        ],
       [2.        +0.j        , 3.        +0.j        ],
       [4.        +0.j        , 0.        +1.41421356j]])

In [28]:
a = np.arange(1, 26).reshape(5, -1)

In [29]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
a * 5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125]])

In [31]:
a + 5

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
b = np.arange(10, 260, 10).reshape(5, -1)

In [34]:
b

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

In [35]:
a * b

array([[  10,   40,   90,  160,  250],
       [ 360,  490,  640,  810, 1000],
       [1210, 1440, 1690, 1960, 2250],
       [2560, 2890, 3240, 3610, 4000],
       [4410, 4840, 5290, 5760, 6250]])

In [36]:
np.matmul(a, b)

array([[ 2150,  2300,  2450,  2600,  2750],
       [ 4900,  5300,  5700,  6100,  6500],
       [ 7650,  8300,  8950,  9600, 10250],
       [10400, 11300, 12200, 13100, 14000],
       [13150, 14300, 15450, 16600, 17750]])

## NumPy - álgebra linear

In [37]:
b = np.random.random(16).reshape(4, 4)
b

array([[0.0875557 , 0.46003998, 0.13586376, 0.49600575],
       [0.71819997, 0.6851916 , 0.74299495, 0.73265467],
       [0.48317866, 0.11720275, 0.50488589, 0.92100005],
       [0.32910784, 0.46154531, 0.09266675, 0.42986605]])

In [38]:
import numpy.linalg as la
la.inv(b)

array([[-3.63801716,  0.02286271,  0.30000617,  3.5160285 ],
       [ 1.35243915,  0.63119115, -1.33320522,  0.22011353],
       [ 1.21250791,  1.81255005, -0.31184381, -3.82020399],
       [ 1.0717964 , -1.08594463,  1.26899481,  0.2216061 ]])

In [39]:
(eigenvalues, eigenvector) = la.eig(b)

In [40]:
eigenvalues

array([ 1.8095383 +0.j        , -0.22210194+0.j        ,
        0.06003144+0.37039409j,  0.06003144-0.37039409j])

In [41]:
eigenvector

array([[ 0.33826908+0.j        ,  0.8849861 +0.j        ,
        -0.22054619+0.11341017j, -0.22054619-0.11341017j],
       [ 0.74591286+0.j        , -0.30252575+0.j        ,
        -0.04386873-0.50717259j, -0.04386873+0.50717259j],
       [ 0.4465772 +0.j        , -0.29854075+0.j        ,
         0.7319557 +0.j        ,  0.7319557 -0.j        ],
       [ 0.36021776+0.j        , -0.19013469+0.j        ,
        -0.23225732+0.2994101j , -0.23225732-0.2994101j ]])

## Pandas

In [42]:
import pandas as pd

In [61]:
dic = { "Coluna 1": ["v1", "v2", "v3", "v4"],
        "Coluna 2": ["v1c2", "v2c2", "v3c2", "v4c2"],
        "Coluna 3": list("ABCD"),
        "Coluna 4": [ 1, 2.5, 3.75, 5 ],
        "Coluna 5": [ 1.1 + 0j, 2, 3, 4 ]}
df_dic = pd.DataFrame(dic, index=["primeira", "segunda", "terceira", "quarta"])

In [62]:
df_dic

Coluna 1 Coluna 2 Coluna 3  Coluna 4  Coluna 5
primeira       v1     v1c2        A      1.00  (1.1+0j)
segunda        v2     v2c2        B      2.50    (2+0j)
terceira       v3     v3c2        C      3.75    (3+0j)
quarta         v4     v4c2        D      5.00    (4+0j)

In [63]:
lista = [["v1", "v1c2", "A"],
         ["v2", "v2c2", "B"],
         ["v3", "v3c2", "C"],
         ["v4", "v4c2", "D"]]

In [64]:
df_lista = pd.DataFrame(lista,
                        index=["primeira", "segunda", "terceira", "quarta"])
df_lista

0     1  2
primeira  v1  v1c2  A
segunda   v2  v2c2  B
terceira  v3  v3c2  C
quarta    v4  v4c2  D

In [65]:
df_lista.columns = ["Coluna 1", "Coluna 2", "Coluna 3"]

In [66]:
df_lista

Coluna 1 Coluna 2 Coluna 3
primeira       v1     v1c2        A
segunda        v2     v2c2        B
terceira       v3     v3c2        C
quarta         v4     v4c2        D

In [67]:
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [68]:
df_array = pd.DataFrame(a,
                        index=range(1, 6),
                        columns=list("ABCDE"))

In [69]:
df_array

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

## Indexing

In [81]:
df = pd.DataFrame(np.arange(1, 26).reshape(5, -1),
                  index=["L0", "L1", "L2", "L3", "L4"],
                  columns=["C0", "C1", "C2", "C3", "C4"])
df

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L1   6   7   8   9  10
L2  11  12  13  14  15
L3  16  17  18  19  20
L4  21  22  23  24  25

#### Usando colchetes

In [82]:
df["C3"]

L0     4
L1     9
L2    14
L3    19
L4    24
Name: C3, dtype: int64

In [83]:
df[2:4]

C0  C1  C2  C3  C4
L2  11  12  13  14  15
L3  16  17  18  19  20

##### Sem ambiguidade: `loc` e `iloc`

In [84]:
df

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L1   6   7   8   9  10
L2  11  12  13  14  15
L3  16  17  18  19  20
L4  21  22  23  24  25

In [85]:
# df.iloc[ linhas,  colunas ]
df.iloc[3, 0]

16

In [86]:
df.iloc[-2:, :2]

C0  C1
L3  16  17
L4  21  22

In [87]:
df.iloc[-2:, -2:]

C3  C4
L3  19  20
L4  24  25

In [88]:
df.iloc[[0, 2, 4], [1, 3]]

C1  C3
L0   2   4
L2  12  14
L4  22  24

In [91]:
df.iloc[:, 3:4]

C3
L0   4
L1   9
L2  14
L3  19
L4  24

In [92]:
df

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L1   6   7   8   9  10
L2  11  12  13  14  15
L3  16  17  18  19  20
L4  21  22  23  24  25

In [95]:
df.loc[:, "C1"]

L0     2
L1     7
L2    12
L3    17
L4    22
Name: C1, dtype: int64

#### `loc` com índices numéricos

In [98]:
df_array

A   B   C   D   E
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25

In [104]:
df_array.loc[5, "A"]

21

##### `at` e `iat`

In [105]:
df

C0  C1  C2  C3  C4
L0   1   2   3   4   5
L1   6   7   8   9  10
L2  11  12  13  14  15
L3  16  17  18  19  20
L4  21  22  23  24  25

In [108]:
df.at["L2", "C3"]

14

In [109]:
df.iat[3, 4]

20

##### _deprecated_: `ix`

In [111]:
df.ix[3, 2]

/home/jtoledo/projects/github/numpy_pandas/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


18

### Operações Básicas

In [112]:
cervejas = pd.DataFrame([["Vedett", "IPA", "Bélgica", 0.33, 5.5],
                         ["Eisenbahn", "Strong Golden Ale", "Brasil", 0.355, 8.0],
                         ["Belhaven", "Rich Scottish Ale", "Escócia", 0.33, 7.4],
                         ["Robinsons", "Premium Britisch Beer", "Inglaterra", 0.5, 4.7],
                         ["Brewdog", "IPA", "Escócia", 0.33, 5.6],
                         ["Fuller's", "Superior Strong Ale", "Inglaterra", 0.5, 8.5],
                         ["Goose", "Session IPA", "Brasil", 0.355, 4.1]],
                        index=["Vedett IPA", "Eisenbahn", "90 Wee Heavy", "Trooper", "Punk IPA", "Golden Pride", "Midway"],
                        columns=["Fabricante", "Tipo", "País", "Volume", "Graduação Alcoólica"])

In [113]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   
Midway            Goose            Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6  
Golden Pride                  8.5  
Midway                        4.1

In [118]:
cervejas.head()

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6

In [119]:
cervejas.head(3)

Fabricante               Tipo     País  Volume  \
Vedett IPA       Vedett                IPA  Bélgica   0.330   
Eisenbahn     Eisenbahn  Strong Golden Ale   Brasil   0.355   
90 Wee Heavy   Belhaven  Rich Scottish Ale  Escócia   0.330   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4

In [120]:
cervejas.tail(2)

Fabricante                 Tipo        País  Volume  \
Golden Pride   Fuller's  Superior Strong Ale  Inglaterra   0.500   
Midway            Goose          Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Golden Pride                  8.5  
Midway                        4.1

In [121]:
cervejas.describe()

Volume  Graduação Alcoólica
count  7.000000             7.000000
mean   0.385714             6.257143
std    0.078868             1.705733
min    0.330000             4.100000
25%    0.330000             5.100000
50%    0.355000             5.600000
75%    0.427500             7.700000
max    0.500000             8.500000

In [126]:
# cervejas.transpose() é a mesma coisa
cervejas.T

Vedett IPA          Eisenbahn       90 Wee Heavy  \
Fabricante              Vedett          Eisenbahn           Belhaven   
Tipo                       IPA  Strong Golden Ale  Rich Scottish Ale   
País                   Bélgica             Brasil            Escócia   
Volume                    0.33              0.355               0.33   
Graduação Alcoólica        5.5                  8                7.4   

                                   Trooper Punk IPA         Golden Pride  \
Fabricante                       Robinsons  Brewdog             Fuller's   
Tipo                 Premium Britisch Beer      IPA  Superior Strong Ale   
País                            Inglaterra  Escócia           Inglaterra   
Volume                                 0.5     0.33                  0.5   
Graduação Alcoólica                    4.7      5.6                  8.5   

                          Midway  
Fabricante                 Goose  
Tipo                 Session IPA  
País                      Brasil  
Volume                     0.355  
Graduação Alcoólica          4.1

In [128]:
cervejas.sort_values(['Volume'])

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
Midway            Goose            Session IPA      Brasil   0.355   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   

              Graduação Alcoólica  
Vedett IPA                    5.5  
90 Wee Heavy                  7.4  
Punk IPA                      5.6  
Eisenbahn                     8.0  
Midway                        4.1  
Trooper                       4.7  
Golden Pride                  8.5

In [127]:
cervejas['Volume'].rank()

Vedett IPA      2.0
Eisenbahn       4.5
90 Wee Heavy    2.0
Trooper         6.5
Punk IPA        2.0
Golden Pride    6.5
Midway          4.5
Name: Volume, dtype: float64

In [129]:
cervejas['Graduação Alcoólica'].max()

8.5

In [130]:
cervejas['Graduação Alcoólica'].idxmax()

'Golden Pride'

In [131]:
cervejas['Graduação Alcoólica'].idxmin()

'Midway'

In [134]:
cervejas

Fabricante                   Tipo        País  Volume  \
Vedett IPA       Vedett                    IPA     Bélgica   0.330   
Eisenbahn     Eisenbahn      Strong Golden Ale      Brasil   0.355   
90 Wee Heavy   Belhaven      Rich Scottish Ale     Escócia   0.330   
Trooper       Robinsons  Premium Britisch Beer  Inglaterra   0.500   
Punk IPA        Brewdog                    IPA     Escócia   0.330   
Golden Pride   Fuller's    Superior Strong Ale  Inglaterra   0.500   
Midway            Goose            Session IPA      Brasil   0.355   

              Graduação Alcoólica  
Vedett IPA                    5.5  
Eisenbahn                     8.0  
90 Wee Heavy                  7.4  
Trooper                       4.7  
Punk IPA                      5.6  
Golden Pride                  8.5  
Midway                        4.1

In [133]:
# parâmetro: lista dos números de linha que quero na resposta]
cervejas.take([2, -2, 4])

Fabricante                 Tipo        País  Volume  \
90 Wee Heavy   Belhaven    Rich Scottish Ale     Escócia    0.33   
Golden Pride   Fuller's  Superior Strong Ale  Inglaterra    0.50   
Punk IPA        Brewdog                  IPA     Escócia    0.33   

              Graduação Alcoólica  
90 Wee Heavy                  7.4  
Golden Pride                  8.5  
Punk IPA                      5.6

In [135]:
cervejas.iloc[[2, 4, -2]]

Fabricante                 Tipo        País  Volume  \
90 Wee Heavy   Belhaven    Rich Scottish Ale     Escócia    0.33   
Punk IPA        Brewdog                  IPA     Escócia    0.33   
Golden Pride   Fuller's  Superior Strong Ale  Inglaterra    0.50   

              Graduação Alcoólica  
90 Wee Heavy                  7.4  
Punk IPA                      5.6  
Golden Pride                  8.5

In [ ]:
cervejas

In [136]:
cervejas.iat[1, 2]

'Brasil'

In [137]:
cervejas.iat[5, 4]

8.5

In [138]:
cervejas.iat[0, 0]

'Vedett'

In [139]:
cervejas.at['Trooper', 'Volume']

0.5

### Loading & Saving

In [140]:
df = pd.read_csv('beers.csv')

In [141]:
df.head()

Unnamed: 0    abv  ibu    id                 name  \
0           0  0.050  NaN  1436             Pub Beer   
1           1  0.066  NaN  2265          Devil's Cup   
2           2  0.071  NaN  2264  Rise of the Phoenix   
3           3  0.090  NaN  2263             Sinister   
4           4  0.075  NaN  2262        Sex and Candy   

                            style  brewery_id  ounces  
0             American Pale Lager         408    12.0  
1         American Pale Ale (APA)         177    12.0  
2                    American IPA         177    12.0  
3  American Double / Imperial IPA         177    12.0  
4                    American IPA         177    12.0

In [145]:
df = pd.read_csv('beers.csv',
                 index_col=0)

In [147]:
df.head()

abv  ibu    id                 name                           style  \
0  0.050  NaN  1436             Pub Beer             American Pale Lager   
1  0.066  NaN  2265          Devil's Cup         American Pale Ale (APA)   
2  0.071  NaN  2264  Rise of the Phoenix                    American IPA   
3  0.090  NaN  2263             Sinister  American Double / Imperial IPA   
4  0.075  NaN  2262        Sex and Candy                    American IPA   

   brewery_id  ounces  
0         408    12.0  
1         177    12.0  
2         177    12.0  
3         177    12.0  
4         177    12.0

In [153]:
goog = pd.read_csv('GOOG.csv',
                   sep=';')
goog.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  19/08/2004  49,676899  51,693783  47,669952  49,845802  49,845802  44994500
1  20/08/2004  50,178635  54,187561  49,925285  53,805050  53,805050  23005800
2  23/08/2004  55,017166  56,373344  54,172661  54,346527  54,346527  18393200
3  24/08/2004  55,260582  55,439419  51,450363  52,096165  52,096165  15361800
4  25/08/2004  52,140873  53,651051  51,604362  52,657513  52,657513   9257400

In [154]:
goog.dtypes

Date         object
Open         object
High         object
Low          object
Close        object
Adj Close    object
Volume        int64
dtype: object

In [155]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',')
goog.head()

Date       Open       High        Low      Close  Adj Close    Volume
0  19/08/2004  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1  20/08/2004  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2  23/08/2004  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3  24/08/2004  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4  25/08/2004  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [156]:
goog.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume         int64
dtype: object

In [158]:
goog.sort_values('Date').head()

Date        Open        High         Low       Close   Adj Close  \
114   01/02/2005   96.561958   97.694588   94.699074   95.329971   95.329971   
366   01/02/2006  193.258041  199.701141  192.507919  199.591843  199.591843   
617   01/02/2007  251.365112  251.370087  239.209167  239.318466  239.318466   
869   01/02/2008  262.626862  266.601013  253.352188  256.283112  256.283112   
1372  01/02/2010  265.572693  266.173798  263.436584  264.787811  264.787811   

        Volume  
114   37922900  
366   54597700  
617   31521000  
869   35429900  
1372   4530800

In [159]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',',
                   parse_dates=[0])
goog.head()

Date       Open       High        Low      Close  Adj Close    Volume
0 2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1 2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2 2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3 2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4 2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [160]:
goog.dtypes

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [161]:
goog.sort_values('Date').head()

Date       Open       High        Low      Close  Adj Close    Volume
9  2004-01-09  51.018177  51.152302  49.512966  49.801090  49.801090   9206800
30 2004-01-10  64.977386  66.686272  64.033524  65.861633  65.861633  15238400
51 2004-01-11  96.149643  98.196327  95.017006  97.381630  97.381630  24608700
72 2004-01-12  90.387115  90.660339  89.194870  89.398552  89.398552  15830400
10 2004-02-09  49.274517  50.854240  49.150326  50.427021  50.427021  15232100

In [162]:
goog.sort_values('Date').tail()

Date         Open         High          Low        Close  \
3663 2019-11-03  1144.449951  1176.189941  1144.449951  1175.760010   
3686 2019-11-04  1203.959961  1207.959961  1200.130005  1204.619995   
3645 2019-12-02  1106.800049  1125.295044  1105.849976  1121.369995   
3664 2019-12-03  1178.260010  1200.000000  1178.260010  1193.199951   
3687 2019-12-04  1210.000000  1218.349976  1208.109985  1217.869995   

        Adj Close   Volume  
3663  1175.760010  1719200  
3686  1204.619995   710200  
3645  1121.369995  1609100  
3664  1193.199951  2013100  
3687  1217.869995   933400

In [163]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',',
                   parse_dates=[0],
                   dayfirst=True)
goog.head()

Date       Open       High        Low      Close  Adj Close    Volume
0 2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1 2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2 2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3 2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4 2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [164]:
goog.sort_values('Date').tail()

Date         Open         High          Low        Close  \
3689 2019-04-16  1225.000000  1230.819946  1220.119995  1227.130005   
3690 2019-04-17  1233.000000  1240.560059  1227.819946  1236.339966   
3691 2019-04-18  1239.180054  1242.000000  1234.609985  1236.369995   
3692 2019-04-22  1235.989990  1249.089966  1228.310059  1248.839966   
3693 2019-04-23  1250.689941  1269.000000  1246.380005  1264.550049   

        Adj Close   Volume  
3689  1227.130005   856300  
3690  1236.339966  1221900  
3691  1236.369995  1331800  
3692  1248.839966   807300  
3693  1264.550049  1319900

In [165]:
goog.sort_values('Date').head()

Date       Open       High        Low      Close  Adj Close    Volume
0 2004-08-19  49.676899  51.693783  47.669952  49.845802  49.845802  44994500
1 2004-08-20  50.178635  54.187561  49.925285  53.805050  53.805050  23005800
2 2004-08-23  55.017166  56.373344  54.172661  54.346527  54.346527  18393200
3 2004-08-24  55.260582  55.439419  51.450363  52.096165  52.096165  15361800
4 2004-08-25  52.140873  53.651051  51.604362  52.657513  52.657513   9257400

In [167]:
goog.dtypes

Date         datetime64[ns]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [169]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',',
                   parse_dates=[0],
                   dayfirst=True,
                   names=["Data", "Abertura", "Máximo", "Mínimo", "Fechamento", "Fechamento Ajustado", "Volume"])
goog.head()

Data   Abertura     Máximo     Mínimo Fechamento Fechamento Ajustado  \
0        Date       Open       High        Low      Close           Adj Close   
1  19/08/2004  49,676899  51,693783  47,669952  49,845802           49,845802   
2  20/08/2004  50,178635  54,187561  49,925285  53,805050           53,805050   
3  23/08/2004  55,017166  56,373344  54,172661  54,346527           54,346527   
4  24/08/2004  55,260582  55,439419  51,450363  52,096165           52,096165   

     Volume  
0    Volume  
1  44994500  
2  23005800  
3  18393200  
4  15361800

In [171]:
goog = pd.read_csv('GOOG.csv',
                   sep=';',
                   decimal=',',
                   parse_dates=[0],
                   dayfirst=True,
                   names=["Data", "Abertura", "Máximo", "Mínimo", "Fechamento", "Fechamento Ajustado", "Volume"],
                   skiprows=1)
goog.head()

Data   Abertura     Máximo     Mínimo  Fechamento  \
0 2004-08-19  49.676899  51.693783  47.669952   49.845802   
1 2004-08-20  50.178635  54.187561  49.925285   53.805050   
2 2004-08-23  55.017166  56.373344  54.172661   54.346527   
3 2004-08-24  55.260582  55.439419  51.450363   52.096165   
4 2004-08-25  52.140873  53.651051  51.604362   52.657513   

   Fechamento Ajustado    Volume  
0            49.845802  44994500  
1            53.805050  23005800  
2            54.346527  18393200  
3            52.096165  15361800  
4            52.657513   9257400

In [170]:
?pd.read_csv